sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

python: 2.7

env:
  matrix:
    - TOXENV=py27-pytest27
    - TOXENV=py27-pytestcurrent
    - TOXENV=py34-pytest27
    - TOXENV=py34-pytestcurrent
    - TOXENV=py35-pytest27
    - TOXENV=py35-pytestcurrent

install:
  - pip install tox

script:
  - tox
