sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

python: 3.5

env:
  - TOXENV=py27-pytest27
  - TOXENV=py27-pytestcurrent
  - TOXENV=py34-pytest27
  - TOXENV=py34-pytestcurrent
  - TOXENV=py35-pytest27
  - TOXENV=py35-pytestcurrent

matrix:
  allow_failures:
    - env: TOXENV=py35-pytest27
    - env: TOXENV=py35-pytestcurrent


install:
  - pip install tox

script:
  - tox
